### ISSUE TITLE
"Cannot read property 'viewBox' of undefined" when building app

### ISSUE THREAD

**Issue by kevinansfield** [ivanvotti/ember-svg-jar#138]
After upgrading from 2.1.0 to 2.2.1 we're no longer able to use `ember serve`, it crashes with the following error

```
>> Build Error (ViewerAssetsBuilder)
>> Cannot read property 'viewBox' of undefined
>> Stack Trace and Error Report: /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/error.dump.3102be7a7bcbebce22c630ea08b2b7f4.log
```

<details>
<summary>Full error report</summary>

```
=================================================================================

ENV Summary:

  TIME: Mon Sep 02 2019 11:59:06 GMT+0100 (British Summer Time)
  TITLE: ember
  ARGV:
  - /Users/kevinansfield/.nvm/versions/node/v10.16.0/bin/node
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin/ember
  - serve
  - --live-reload-base-url=/ghost/
  - --live-reload-port=4201
  EXEC_PATH: /Users/kevinansfield/.nvm/versions/node/v10.16.0/bin/node
  TMPDIR: /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /Users/kevinansfield/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/core/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/node_modules/.bin
  - /Users/kevinansfield/code/ghost/node_modules/.bin
  - /Users/kevinansfield/code/node_modules/.bin
  - /Users/kevinansfield/node_modules/.bin
  - /Users/node_modules/.bin
  - /node_modules/.bin
  - /Users/kevinansfield/.nvm/versions/node/v10.16.0/bin
  - /Users/kevinansfield/.rvm/gems/ruby-2.3.3/bin
  - /Users/kevinansfield/.rvm/gems/ruby-2.3.3@global/bin
  - /Users/kevinansfield/.rvm/rubies/ruby-2.3.3/bin
  - /Users/kevinansfield/.yarn/bin
  - /Users/kevinansfield/.nvm/versions/node/v10.16.0/bin
  - /usr/local/opt/php@7.1/sbin
  - /usr/local/opt/php@7.1/bin
  - /usr/local/heroku/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/local/share/npm/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/kevinansfield/.rvm/bin
  - /Users/kevinansfield/.composer/vendor/bin
  PLATFORM: darwin x64
  FREEMEM: 40435712
  TOTALMEM: 17179869184
  UPTIME: 1116703
  LOADAVG: 3.283203125,2.4765625,2.64990234375
  CPUS:
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.34.0
  - node: 10.16.0
  - openssl: 1.1.1b
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.52
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'viewBox' of undefined
    at getGridSize (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:56:43)
    at filePaths.map (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:95:31)
    at Array.map (<anonymous>)
    at ViewerAssetsBuilder.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:93:34)
    at /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  - code: [undefined]
  - codeFrame: Cannot read property 'viewBox' of undefined
  - errorMessage: Cannot read property 'viewBox' of undefined
        at ViewerAssetsBuilder
-~- created here: -~-
    at ViewerAssetsBuilder.Plugin (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ViewerAssetsBuilder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:72:5)
    at viewerBuilderTrees.svgJarOptions.strategy.map (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:135:14)
    at Array.map (<anonymous>)
    at Class.getViewerTree (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:130:58)
    at Class.treeForPublic (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:41:23)
    at Class.superWrapper [as treeForPublic] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/addon.js:701:33)
    at Class.treeFor (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/addon.js:661:21)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot read property 'viewBox' of undefined
        at ViewerAssetsBuilder
-~- created here: -~-
    at ViewerAssetsBuilder.Plugin (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ViewerAssetsBuilder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:72:5)
    at viewerBuilderTrees.svgJarOptions.strategy.map (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:135:14)
    at Array.map (<anonymous>)
    at Class.getViewerTree (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:130:58)
    at Class.treeForPublic (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/index.js:41:23)
    at Class.superWrapper [as treeForPublic] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/addon.js:701:33)
    at Class.treeFor (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/addon.js:661:21)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: ViewerAssetsBuilder
  - originalErrorMessage: Cannot read property 'viewBox' of undefined
  - stack: TypeError: Cannot read property 'viewBox' of undefined
    at getGridSize (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:56:43)
    at filePaths.map (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:95:31)
    at Array.map (<anonymous>)
    at ViewerAssetsBuilder.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-svg-jar/lib/viewer-assets-builder.js:93:34)
    at /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)

=================================================================================

```

</details>

Our ember-svg-jar config is fairly straightforward, the main thing being explicit source directories:

```javascript
        svgJar: {
            strategy: 'inline',
            stripPath: false,
            sourceDirs: [
                'public/assets/icons',
                'lib/koenig-editor/public/icons'
            ],
            optimizer: {
                plugins: [
                    {prefixIds: true},
                    {cleanupIds: false},
                    {removeDimensions: true},
                    {removeTitle: true},
                    {removeXMLNS: true},
                    // Transforms on groups are necessary to work around Firefox
                    // not supporting transform-origin on line/path elements.
                    {convertPathData: {
                        applyTransforms: false
                    }},
                    {moveGroupAttrsToElems: false}
                ]
            }
        }
```

**Comment by ivanvotti** [comment]
One of your SVG files has no content `public/assets/icons/background-filler.svg`. `ember-svg-jar` expects that source files are not empty.

**Comment by kevinansfield** [comment]
Ohh, good catch, I'd missed that! I've deleted the empty svg and 2.2.1 is working.

Feel free to close this issue if you're not using it to track empty files being ignored 🙂

**Comment by ivanvotti** [comment]
Fixed in `v.2.2.2`
