### ISSUE TITLE
ENOENT: no such file or directory, open 'symbols-loader.html'

### ISSUE THREAD

**Issue by jkerekes-ccc** [ivanvotti/ember-svg-jar#139]
I get **ENOENT: no such file or directory, open 'symbols-loader.html'**  error running `ember install ember-svg-jar`

os: win32 x64  (windows 10)
Node: 10.16.2 (with 12.7.0 too)
ember-cli: 3.11.0  ( with 3.12.0 too)

step to reproduce:

1. create a new project running: `ember new project_name`
2. go to project folder and run  `ember install ember-svg-jar`

you will see something like:
![image](https://user-images.githubusercontent.com/52962411/64617223-c30f2800-d3e6-11e9-90d0-5d532c44b0c6.png)

I looked into it and it seems the following change in `lib/index.js` causes the crash:
```javascript
const path = require('path-posix');
```
*( console log `path.join(__dirname, '../symbols-loader.html')`  and you get `symbols-loader.html` insetead of `C:\tmp\super-rentals2\node_modules\ember-svg-jar\symbols-loader.html`)*

by changing back to use the old path:
```javascript
const path = require('path');
```
works fine.

<details><summary>Full error</summary>

```bash
=================================================================================

ENV Summary:

  TIME: Tue Sep 10 2019 15:54:43 GMT+0300 (Eastern European Summer Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Program Files\nodejs\node_modules\ember-cli\bin\ember
  - install
  - ember-svg-jar
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\user\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Users\user\AppData\Roaming\nvm;C
  - \Program Files\nodejs;C
  - \Users\user\AppData\Local\Microsoft\WindowsApps;C
  - \Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\user\AppData\Local\Programs\Git\cmd;C
  - \Users\user\AppData\Local\GitHubDesktop\bin
  PLATFORM: win32 x64
  FREEMEM: 7845412864
  TOTALMEM: 17078120448
  UPTIME: 9653
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz - 2295
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 4
  - nghttp2: 1.39.1
  - node: 12.7.0
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.30.1
  - v8: 7.5.288.22-node.16
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: ENOENT
  - codeFrame: [undefined]
  - errorMessage: ENOENT: no such file or directory, open 'symbols-loader.html'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: ENOENT: no such file or directory, open 'symbols-loader.html'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: ENOENT: no such file or directory, open 'symbols-loader.html'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.<anonymous> (C:\tmp\super-rentals2\node_modules\ember-svg-jar\lib\index.js:17:32)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\tmp\super-rentals2\node_modules\ember-svg-jar\index.js:3:18)

=================================================================================
```
and here is as a file:
[error.dump.e50fe8603ef7b378a57ef9ce76889b0e.log](https://github.com/ivanvotti/ember-svg-jar/files/3595891/error.dump.e50fe8603ef7b378a57ef9ce76889b0e.log)

</details>

**Comment by marialomidze** [comment]
Also running into this.
