### ISSUE TITLE
Cannot load ember-svg-jar, `Cannot find module './lib/index'`

### ISSUE THREAD

**Issue by tastycode** [ivanvotti/ember-svg-jar#17]
Using ember-cli 1.13, with node 6.5. 
```
17:27:08 ember.1 | (node:16793) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
17:27:10 ember.1 | Cannot find module './lib/index'
17:27:10 ember.1 | Error: Cannot find module './lib/index'
17:27:10 ember.1 |   at Function.Module._resolveFilename (module.js:455:15)
17:27:10 ember.1 |   at Function.Module._load (module.js:403:25)
17:27:10 ember.1 |   at Module.require (module.js:483:17)
17:27:10 ember.1 |   at require (internal/module.js:20:19)
17:27:10 ember.1 |   at Object.<anonymous> (/Users/tastycode/workspace/countable/vendor/javascripts/countable/node_modules/ember-svg-jar/index.js:1:80)
17:27:10 ember.1 |   at Module._compile (module.js:556:32)
17:27:10 ember.1 |   at Object.Module._extensions..js (module.js:565:10)
17:27:10 ember.1 |   at Module.load (module.js:473:32)
17:27:10 ember.1 |   at tryModuleLoad (module.js:432:12)
17:27:10 ember.1 |   at Function.Module._load (module.js:424:3)
17:27:10 ember.1 |   at Module.require (module.js:483:17)
17:27:10 ember.1 |   at require (internal/module.js:20:19)
```

Looking at the source. I see in `./index.js` we `require('./lib/index')` but there is no such directory called `lib` anywhere in the repo. How can this possibly work?

**Comment by ivanvotti** [comment]
The addon is not supposed to be installed from the GitHub repo directly. You need to install it from the NPM registry.

There's a build step that is required to get a working NPM package (check out package.json). Also when I publish the NPM package I build the asset viewer into the public directory.

**Comment by tastycode** [comment]
Confirmed! Thanks for the help!
