### ISSUE TITLE
Template Only Strategy Might be Broken

### ISSUE THREAD

**Issue by jherdman** [ivanvotti/ember-svg-jar#191]
#### Describe the bug

Given:

```handlebars
<Svg @name="icon" />
```

Where exists:

```
public/icon.svg
```

1. We're missing the `ember-cli-resolve-asset` package
2. After installing this package:

```
Error: ember-cli-resolve-asset: Could not find 'ember-svg-jar/components/icon.js' in the asset map.
     at getAssetPath (http://localhost:7357/assets/vendor-f347f06b9a927d124d62a02d2ec78022.js:66965:13)
     at resolveAsset (http://localhost:7357/assets/vendor-f347f06b9a927d124d62a02d2ec78022.js:66986:12)
     at async loadSvg (http://localhost:7357/assets/vendor-f347f06b9a927d124d62a02d2ec78022.js:68063:23)
     at async Svg.updateSvg (http://localhost:7357/assets/vendor-f347f06b9a927d124d62a02d2ec78022.js:68088:30)
--
```

#### Reproduce the bug

See #190

#### Expected behavior

It embeds the correct SVG.

**Comment by jherdman** [comment]
@betocantu93 I may have merged the template-only strategy prematurely. Would you be able to help me with the above? I've pushed a branch with the reproduction.

**Comment by betocantu93** [comment]
I think the strategy prefixes the component names and it's also configurable...

```hbs
<Svg @name="svg/icon" />
```

**Comment by jherdman** [comment]
@betocantu93 sorry for being so slow on this, it's been busy as of late. I'm going to try and get back up to speed on this issue ASAP.

**Comment by betocantu93** [comment]
@jherdman no worries! let me know how I can help.
