### ISSUE TITLE
BroccoliMergeTrees fails if there are .DS_Store files

### ISSUE THREAD

**Issue by mupkoo** [ivanvotti/ember-svg-jar#20]
I have defined couple of source directories and from the looks of it, there are `.DS_Store` files which cause the `MergeTrees` to fail.

<details>
  <summary>Error output</summary>
<pre>
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Merge error: file .DS_Store exists in /apps/frontend/tmp/broccoli_merge_trees-input_base_path-NE9wvtwR.tmp/0 and /apps/frontend/tmp/broccoli_merge_trees-input_base_path-NE9wvtwR.tmp/1
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at BroccoliMergeTrees._mergeRelativePath (/apps/frontend/node_modules/broccoli-merge-trees/index.js:274:17)
    at BroccoliMergeTrees.build (/apps/frontend/node_modules/broccoli-merge-trees/index.js:82:24)
    at /apps/frontend/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/apps/frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/apps/frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/apps/frontend/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/apps/frontend/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/apps/frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/apps/frontend/node_modules/broccoli-merge-trees/index.js:42:10)
    at mergeTreesIfNeeded (/apps/frontend/node_modules/ember-svg-jar/lib/index.js:22:42)
    at CoreObject.<anonymous> (/apps/frontend/node_modules/ember-svg-jar/lib/index.js:129:31)
    at CoreObject.optimizedSvgsFor (/apps/frontend/node_modules/ember-svg-jar/lib/index.js:30:45)
    at CoreObject.getInlineStrategyTree (/apps/frontend/node_modules/ember-svg-jar/lib/index.js:181:34)
    at CoreObject.treeForApp (/apps/frontend/node_modules/ember-svg-jar/lib/index.js:73:23)
    at CoreObject._treeFor (/apps/frontend/node_modules/ember-cli/lib/models/addon.js:371:33)
    at CoreObject.treeFor (/apps/frontend/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /apps/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:498:20
</pre>
</detail>

**Comment by macgyver** [comment]
I have a sort of related issue.. I have an Ember app that is importing an addon and they each have an svg file with the same name. When I `npm link` the addon from its source code (vs. installing it to `node_modules`) I get essentially the same error. I honestly have no idea why `npm link` should make any difference, but it seems to..
