### ISSUE TITLE
Make ember-svg-jar compatible with windows

### ISSUE THREAD

**Issue by jonasbuechel** [ivanvotti/ember-svg-jar#24]
Hi there

Since I'm using the ember-svg-jar I've got a build problem at Windows. For osx it works fine.
According to the attached error message: Is there any problem with file-permissions, pathlengts or something like this? 
Please write, if you need some more specific informations, I unfortunately found nothing close to the given error message.

Thanks! 

Config: (ember-cli-build)

    svgJar: {
          strategy: ['symbol', 'inline'],

          symbol: {
            sourceDirs: ['svgs', 'public/assets/svg/symbol'],
            outputFile: '/assets/svg/symbol/symbols.svg',
            includeLoader: true
          },

          inline: {
            sourceDirs: ['svgs', 'public/assets/svg/inline']
          }
        },

Error:

    File: icon_arrow-down--dark.svg
    The Broccoli Plugin: [SVGOFilter] failed with:
    Error: ENOENT: no such file or directory, open 'C:\Users\MYUSER\AppData\Local\Temp\if-you-need-to-delete-this-open-an-issue-async-disk-cache\4e4f4cd6c3ab8e68f1af5bdeb24f06f3255c1917\{"persist":true,"svgoConfig":{}}627fdc20a3017e3b3616d693aed14551'
        at Error (native)

    The broccoli plugin was instantiated at:
        at SVGOFilter.Plugin (C:\workspaces\my_repos\my-project\node_modules\broccoli-plugin\index.js:7:31)
        at SVGOFilter.Filter [as constructor] (C:\workspaces\my_repos\my-project\node_modules\broccoli-persistent-filter\index.js:60:10)
        at new SVGOFilter (C:\workspaces\my_repos\my-project\node_modules\broccoli-svg-optimizer\index.js:15:10)
        at CoreObject.<anonymous> (C:\workspaces\my_repos\my-project\node_modules\ember-svg-jar\lib\index.js:135:18)
        at CoreObject.optimizedSvgsFor (C:\workspaces\my_repos\my-project\node_modules\ember-svg-jar\lib\index.js:30:45)
        at CoreObject.getInlineStrategyTree (C:\workspaces\my_repos\my-project\node_modules\ember-svg-jar\lib\index.js:181:34)
        at CoreObject.treeForApp (C:\workspaces\my_repos\my-project\node_modules\ember-svg-jar\lib\index.js:73:23)
        at CoreObject._treeFor (C:\workspaces\my_repos\my-project\node_modules\ember-cli\lib\models\addon.js:373:33)
        at CoreObject.treeFor (C:\workspaces\my_repos\my-project\node_modules\ember-cli\lib\models\addon.js:341:21)
        at C:\workspaces\my_repos\my-project\node_modules\ember-cli\lib\broccoli\ember-app.js:498:20

**Comment by jonasbuechel** [comment]
I think the colon in the temp filename isn't supported at Windows: 'svgoConfig":{}}627fdc20a3017e3b3616d693aed14551'

Is there a way to go without colons?

**Comment by jonasbuechel** [comment]
I think it can be the same problem like in this extension: https://github.com/chrislopresto/ember-freestyle/issues/72

**Comment by les2** [comment]
maybe run the json through encodeURIComponent (assuming all those chars are
safe for Windows paths).

that or url safe base 64 encoding.

**Comment by jonasbuechel** [comment]
Temporary solution for me: Disable the optimizer

`
svgJar: {
  optimizer: false
}
`

**Comment by XaserAcheron** [comment]
Just submitted a [new PR](https://github.com/ivanvotti/broccoli-svg-optimizer/pull/2) for this. Hooray for Windows-taming. :P

**Comment by ivanvotti** [comment]
@XaserAcheron Thanks.

**Comment by ivanvotti** [comment]
It turns out the `broccoli-svg-optimizer` is not the only reason why it doesn't work for Windows. I've installed Windows and am going to fix the rest Windows related problems shortly, probably it will be done today.
