### ISSUE TITLE
Cannot read property 'strategy' of undefined when included in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by jeanduplessis** [ivanvotti/ember-svg-jar#49]
In my Ember add-on if I include this add-on in `devDependencies` it all works fine.
However when I try to move it to `dependencies` in package.json it fails to build with the message below.

```node
Cannot read property 'strategy' of undefined
TypeError: Cannot read property 'strategy' of undefined
    at Class.hasInlineStrategy (/Users/jdp/Development/sui-lib/node_modules/ember-svg-jar/lib/index.js:231:31)
    at Class.treeForApp (/Users/jdp/Development/sui-lib/node_modules/ember-svg-jar/lib/index.js:124:14)
    at Class._treeFor (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/models/addon.js:557:33)
    at Class.treeFor (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/models/addon.js:517:21)
    at addons.reduce (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/models/addon.js:384:26)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/models/addon.js:381:24)
    at Class.treeFor (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/models/addon.js:516:22)
    at project.addons.reduce (/Users/jdp/Development/sui-lib/node_modules/ember-cli/lib/broccoli/ember-app.js:630:25)
    at Array.reduce (<anonymous>)
```

```
$ ember -v                                                                                                                                                                                     
ember-cli: 2.17.1
node: 8.7.0
os: darwin x64
```

**Comment by ivanvotti** [comment]
The problem should be fixed in #52 and is available in the latest ember-svg-jar release `v1.0.0`.
