### ISSUE TITLE
Ember 3.3 copy-copyable deprecation

### ISSUE THREAD

**Issue by scottkidder** [ivanvotti/ember-svg-jar#88]
Found the following DEPRECATION warning in our tests:

```
 { type: 'warn',
              text:
               '\'DEPRECATION: Use ember-copy addon instead of copy method and Copyable mixin. [deprecation id: ember-runtime.deprecate-copy-copyable] See https://emberjs.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable for more details.\\n        at logDeprecationStackTrace (http://localhost:46003/assets/vendor.js:25079:29)\\n        at HANDLERS.(anonymous function) (http://localhost:46003/assets/vendor.js:25181:17)\\n        at raiseOnDeprecation (http://localhost:46003/assets/vendor.js:25103:17)\\n        at HANDLERS.(anonymous function) (http://localhost:46003/assets/vendor.js:25181:17)\\n        at invoke (http://localhost:46003/assets/vendor.js:25190:17)\\n        at deprecate (http://localhost:46003/assets/vendor.js:25162:34)\\n        at Object.copy (http://localhost:46003/assets/vendor.js:60519:47)\\n        at inlineSvgFor (http://localhost:46003/assets/vendor.js:226523:52)\\n        at makeSvg (http://localhost:46003/assets/vendor.js:226538:57)\'\n' }
```

**Comment by scottkidder** [comment]
Nevermind I see that this is fixed on master. Maybe make a release?

**Comment by ivanvotti** [comment]
Done

**Comment by scottkidder** [comment]
Thanks @ivanvotti
